### ISSUE TITLE
SSL Issue when running a get command in Plain Text on MacOS

### ISSUE THREAD

**Issue by maeld974** [asreview/synergy-dataset#100]
I received an ssl.SSLCertVerificationError: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)` error when trying to run the `synergy_dataset get` on macOS Ventura Version 13.6.6.

It is a known issue on MacOS that I was able to solve using the `open /Applications/Python\ 3.9/Install\ Certificates.command` in a terminal.

This is a common issue on macOS where Python is not able to verify the SSL certificate provided by the server. To fix it we are using Certificates.command script from python.org for macOS.

**Comment by jteijema** [comment]
I can verify this happening on more machines running OSx.

`open /Applications/Python\ 3.13/Install\ Certificates.command` solves this issue for me too.
