### ISSUE TITLE
Allow multiple files as input in enrich script

### ISSUE THREAD

**Issue by EmilyWes** [asreview/synergy-dataset#105]
Currently the enrich script assumes 1 file with labelled data. 
A lot of authors put the data online in different files, for example 1 file for the search and 1 file for the inclusions. 
To avoid code duplication in gathering(composing) the data, I suggest enhancing the enrich script to merge the available files.
This way of working is also beneficial when/if we add title/abstract inclusions via a separate file.

**Comment by Rensvandeschoot** [comment]
For this, I think we can use the [Compose](https://github.com/asreview/asreview-datatools?tab=readme-ov-file#data-compose-experimental) functionality, which allows multiple input files and outputs a single file.

**Comment by EmilyWes** [comment]
I just had a nice conversation with Jonathan. The takeaways:
- We want to avoid the code duplication in the compose scripts.
- We want to keep the enrich script single purpose.

Solution:
- Create a utils script with functionality for the code that is often used in the compose scripts, so that the compose script can simply call some functions of this utils scripts.

For this Issue I will just create the utils script and some comments of the functions I intent to add.
I will add the functions in separate issues + PR's
